# Generated by Django 5.1.7 on 2025-04-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0002_notification_notificatio_is_read_51e701_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_is_read_51e701_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_created_ca1755_idx',
        ),
    ]
