# Generated by Django 5.2 on 2025-05-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals_app', '0002_populate_rentals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
