services:
  frontend:
    build:
      context: ./frontend  # Folder containing the frontend Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map host port 3000 to container port 3000
    environment:
      - REACT_APP_FLUTTERWAVE_PUBLIC_KEY=${REACT_APP_FLUTTERWAVE_PUBLIC_KEY}  # Load from .env file
    volumes:
      - ./frontend:/app  # Mount the frontend code into the container
      - /app/node_modules  # Avoid overwriting node_modules inside the container
    working_dir: /app  # Set the working directory inside the container
    command: npm start  # Start the React development server
    depends_on:
      - backend  # Ensure the backend service starts before the frontend

  backend:
    build:
      context: ./backend  # Folder containing the backend Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    volumes:
      - ./backend:/app  # Mount the backend code into the container
      - ./backend/db.sqlite3:/app/db.sqlite3  # Persist SQLite database outside the container
    environment:
      - PYTHONUNBUFFERED=1  # Ensure Python logs are flushed immediately
    command: python manage.py runserver 0.0.0.0:8000  # Start the Django development server