# Generated by Django 5.1.7 on 2025-03-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_booking_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('Online', 'Online'), ('Physical', 'Physical')], default='Physical', max_length=50),
        ),
    ]
